global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-prod'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "hosts_rules.yml"
  - "containers_rules.yml"
  - "services_rules.yml"
  
# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus-node-exporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'prometheus-cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus-pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
        - sd/targets-node-exporter.yml
        
  - job_name: 'cadvisor'
    file_sd_configs:
      - files:
        - sd/targets-cadvisor.yml

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
